[package]
name = "x402-reqwest"
version = "0.2.0"
edition = "2024"
description = "Wrapper for reqwest for transparent x402 payments"
license = "Apache-2.0"
authors = ["Sergey Ukustov <sergey@ukstv.me>"]
repository = "https://github.com/x402-rs/x402-rs"
homepage = "https://x402.rs"
documentation = "https://docs.rs/x402-reqwest"
keywords = ["axum", "middleware", "x402", "payments", "stablecoin"]
categories = ["web-programming::http-client", "authentication", "cryptography", "finance", "network-programming"]
readme = "README.md"

[dependencies]
x402-rs = { version = "0.7", default-features = false }
reqwest = { version = "0.12.20" }
http = { version = "1.3.1" }
reqwest-middleware = { version = "0.4.2" }
tokio = { version = "1.45.1" }
async-trait = { version = "0.1.88" }
alloy = { version = "1.0" }
rand = { version = "0.9.1" }
serde_json = { version = "1.0.140" }
thiserror = { version = "2.0.12" }
base64 = { version = "0.22.1" }
solana-sdk = { version = "2.3.1", features = ["full"] }
solana-client = { version = "2.3.7" }
spl-token = { version = "8.0.0" }
spl-token-2022 = { version = "9.0.0" }
spl-associated-token-account = { version = "7.0.0" }

# Gear/Vara
gsdk = { version = "1.9.1" }

extended-vft-client ={ version = "*", path = "../../../standards/extended-vft/client" }

bincode = { version = "1.3.3" } # Older version due to compatibility with solana-sdk

# Telemetry
tracing = { version = "0.1.41" }

[features]
telemetry = ["x402-rs/telemetry"]
